apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-svc
  namespace: luegm-stud-dev
spec:
  type: NodePort
  ports:
  - name: todo-svc
    port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: todo-app
  